openapi: 3.0.0
info:
  title: Basic Auth Example
  version: '1.0'
  description: Maneiro


paths:
  /secret:
    get:
      summary: Return secret string
      operationId: load_server3.controllers.app.get_secret
      responses:
        '200':
          description: secret response
          content:
            '*/*':
              schema:
                type: string
      security:
        - basic: []
components:
  securitySchemes:
    oauth2:
      type: oauth2
      x-tokenInfoFunc: load_server3.controllers.app.dummy_func
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth2/dialog
          scopes:
            secret: Allow accessing secret
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: load_server3.controllers.app.basic_auth