# openapi: 3.0.0
# info:
#   description: teste de carga
#   version: "1"
#   title: teste de carga
# tags:
#   - name: teste
#     description: teste de carga
# paths:
#   "/hello/{name}":
#     get:
#       tags:
#         - teste
#       summary: ""
#       description: ""
#       operationId: get_hello
#       parameters:
#         - name: name
#           in: path
#           required: true
#           schema:
#             type: string
#       responses:
#         "200":
#           description: hello world
#       x-swagger-router-controller: load_server.controllers.teste_controller_async
# servers:
#   - url: https://0.0.0.0:8080
#   - url: http://0.0.0.0:8080


openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:8080/v1

paths:
  /hello/{name}:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: load_server.controllers.teste_controller_async.get_hello
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello dave!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            type: string
            example: "dave"