openapi: 3.0.0
info:
  title: Basic Auth Example
  version: '1.0'
  description: Maneiro

servers:
  - url: http://{host}:{port}/v1
    variables:
      host:
        default: 0.0.0.0
        description: ip address
      port:
        enum:
          - '443'
          - '8080'
        default: '8080'

paths:
  /secret:
    get:
      summary: Return secret string
      operationId: load_server1.controllers.app.get_secret
      responses:
        '200':
          description: secret response
          content:
            '*/*':
              schema:
                type: string
      security:
        - basic: []

components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
    basic:
      type: http
      scheme: basic
      x-basicInfoFunc: load_server1.controllers.app.basic_auth